version: '3.5'


services:
  postgres:
    container_name: nest_pg
    image: postgres:latest
    hostname: postgres
    restart: always
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env


volumes:
  postgres-db:
    driver: local
    name: nest-db
